name: world
description: A new Flutter game.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  auto_size_text: ^3.0.0
  device_preview: ^1.0.0
  sizer: ^2.0.15
  #connectivity_plus: ^2.1.0
  location: ^4.3.0
  country_state_city_picker: ^1.2.7
  cupertino_icons: ^0.1.2
  geolocator:
  google_fonts: null
  http: ^0.13.4
  image_picker: ^0.8.4+4
  #intl: null
  progress_dialog: ^1.1.0+1
  rounded_floating_app_bar: ^0.1.0
  #searchable_dropdown: ^1.1.2
  timezone: null
  video_player: ^2.2.7
  image_cropper: ^1.4.0
  flutter_inappwebview: 
  flutter_dialogs:
  pull_to_refresh: ^2.0.0
  get: ^4.3.8
  date_time_picker: ^2.1.0
  dropdown_search: ^2.0.1
  pinput:
  badges:
  onboarding: ^3.0.0
  flutter_svg: ^1.0.3
  carousel_slider: ^4.0.0
  introduction_screen: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  autocomplete_textfield: ^1.7.3
  country_code_picker: ^2.0.1
  #diacritic: ^0.1.1
  #flutter_country_picker: ^0.1.6
  #flutter_datetime_picker: 1.2.5
  flutter_launcher_icons: ^0.9.2
  fluttertoast: ^8.0.6
  share: 0.6.4
  shared_preferences: ^2.0.6
  dotted_line: ^3.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon1.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/appicon1.png
    - assets/images/star.png
    - assets/images/mastercardimg.png
    - assets/images/visaimg.png
    - assets/images/paypalimg.png
    - assets/images/instanteftimg.png
    - assets/images/bitcoinimg.png
    - assets/images/mobicred.png
    - assets/images/masterpassimg.png
    - assets/images/scode.png
    - assets/images/round_promo_btn.png
    - assets/images/head.png
    - assets/images/founditicon.png
    - assets/images/huntoptionicon.png
    - assets/images/prizeimage.png
    - assets/images/chohooappbar.png
    - assets/images/triangle.png
    - assets/images/keyicon.png
    - assets/images/submitbtnicon.png
    - assets/images/sendphotoiconbtn.png
    - assets/images/ph.png
    - assets/images/secure.png
    - assets/images/appicon/chohooappicon.png
    - assets/images/secretnoimg.png
    - assets/splash/splash_icon.png
    - assets/splash/main_scr_img.png
    - assets/splash/chohoo_img.png
    - assets/images/background_white/background.png
    - assets/images/adidis_logo/adidis_logo.png
    - assets/images/head_red/head_red.png
    - assets/images/forward_white/forward_white.png
    - assets/images/clue_key/clue_key.png
    - assets/images/track_record/track_record.png
    - assets/images/triangle/
    - assets/images/cards_logo/
    - assets/images/locks/
    - assets/images/camera/camera.png
    - assets/images/add_white/add_white.png
    - assets/images/share/
    - assets/images/or/
    - assets/images/bottom_bar/
    - assets/images/placeholder/
    - assets/images/prize_image/prize_image.png
    - assets/images/new_prize_image/new_prize_image.png
    - assets/images/red_head_square/red_head_square.png
    - assets/images/adidas_circular_corners/adidas_circular_corners.png
    - assets/images/red_head_circular_corners/red_head_circular_corners.png
    - assets/images/splash_bg.jpg
    - assets/images/splash_bg_new.jpg
    - assets/videos/ChoohooPortraitSml.mp4
    - assets/country.json
    - assets/images/gift.png
    - assets/onboarding/
    - assets/svg-icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_light.ttf
          weight: 200
        - asset: assets/fonts/roboto_italic.ttf
          weight: 300
        - asset: assets/fonts/roboto_regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_bold.ttf
          weight: 500

dependency_overrides:
  platform: ^3.1.0
  #intl: ^0.17.0-nullsafety.2

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
